### ISSUE TITLE
User and Pass on android?

### ISSUE THREAD

**Issue by x011** [qwj/python-vpn#5]
"IPSec IKE PSK"  doesn't exist on android, just google it and you'll see no results.
What's the username and password that needs to be used on android?
It's funny how you call other programs "stupid", but yours is the one I'd more trouble setting up.

**Comment by kyleharte** [comment]
Don't use IKE, it's not secure! Use IKEv2

**Comment by testcaoy7** [comment]
As a matter of fact, both IPsec XAuth PSK and L2TP/IPsec PSK on Android forces user to enter user name and password.
The best way to use this VPN's IPsec protocol, I believe, is to use a Mac or Linux.
I use macOS Mojave with IKEv2 PSK protocol and it works perfectly.

**Comment by testcaoy7** [comment]
@qwj Maybe you can hard encode a default username and password ? Such as use user as username and passwd as default password. Both Windows and Android force user to enter their User/Pass of their VPN account  even when the protocol is IPSec-PSK.
